name: Comment on Issue

on:
  issues:
    types: [opened, edited, reopened]

jobs:
  testRoute:
    name: Call maintainers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.sender.login != 'issuehunt-oss[bot]'
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
      - uses: pnpm/action-setup@v2
=======
      - uses: pnpm/action-setup@v3
>>>>>>> 7ddf992fa7aab3d9ca976af8003f7771d3c3b35f
        with:
          version: 8
      - uses: actions/setup-node@v4 # just need its cache
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install dependencies (pnpm) # needed since we need to parse markdown, so we also use got instead
        run: pnpm i
      - name: Generate feedback
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/scripts/workflow/test-issue/call-maintainer.js`)
            return script({ github, context, core })
